AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance creation'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI ID (us-east-1)
      Tags:
        - Key: Name
          Value: MyEC2Instance
