name: Deploy EC2 Instance

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug - Check AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws sts get-caller-identity
        if [ $? -ne 0 ]; then
          echo "AWS CLI command failed. Checking credential format:"
          echo "Access Key ID length: ${#AWS_ACCESS_KEY_ID}"
          echo "Secret Access Key length: ${#AWS_SECRET_ACCESS_KEY}"
          exit 1
        fi

    - name: Deploy to AWS CloudFormation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws cloudformation deploy \
          --template-file ec2-template.yaml \
          --stack-name my-ec2-stack \
          --parameter-overrides InstanceType=t2.micro \
          --capabilities CAPABILITY_IAM
