name: Deploy EC2 using CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./cloudformation-template.yml \
            --stack-name my-ec2-stack \
            --parameter-overrides SecurityGroupDescription="Allow HTTP and SSH access" KeyName="${{ secrets.EC2_KEY_PAIR }}" \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Describe CloudFormation stack outputs
        run: |
          aws cloudformation describe-stacks --stack-name my-ec2-stack --query "Stacks[0].Outputs" > stack-output.json

      - name: Get Elastic IP
        id: get_elastic_ip
        run: |
          EIP=$(jq -r '.[] | select(.OutputKey=="ElasticIP") | .OutputValue' stack-output.json)
          echo "::set-output name=ELASTIC_IP::$EIP"

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ steps.get_elastic_ip.outputs.ELASTIC_IP }} 'bash -s' < deploy-script.sh

